#!/usr/bin/env bash
# Configure the local macOS workstation as a Kerberos client for the
# HV.LAB demo realm. Idempotent: re-running just re-renders krb5.conf,
# skips brew install if krb5 is already there, dedups /etc/hosts, and
# refreshes the TGT in the FILE ccache.
#
# Invoked by `task lab:client-setup`; can also be run directly. See
# examples/lab/kerberos/README.md Phase 3 for the surrounding context.

set -euo pipefail

if [ "$(uname -s)" != "Darwin" ]; then
    echo "client-setup.sh: macOS-only (uname -s = $(uname -s))" >&2
    exit 1
fi

: "${HVLAB_ADMIN_PASSWORD:?set HVLAB_ADMIN_PASSWORD in .env.local (lab Administrator password)}"

# Pinned values for the demo realm. The bench's portproxy from Phase 2
# forwards 88/389 to the DC at 10.10.0.10, so both names point at the
# bench's public IP.
REALM="HV.LAB"
DC_FQDN="hv-dc-01.hv.lab"
BENCH_FQDN="hv-bench-01.hv.lab"
BENCH_IP="${HYPERV_HOST:-192.168.3.77}"
KRB5_CONF="$HOME/.config/krb5.conf"
CCACHE="FILE:/tmp/krb5cc_$(id -u)"
KINIT="/opt/homebrew/opt/krb5/bin/kinit"
KLIST="/opt/homebrew/opt/krb5/bin/klist"
KVNO="/opt/homebrew/opt/krb5/bin/kvno"

# 1. MIT krb5 from brew. macOS ships Heimdal at /usr/bin/kinit, but it
# defaults to API: (Keychain) ccache which jcmturner/gokrb5 can't read.
# Brew krb5 keeps everything on FILE: ccache and matches the standard
# Linux-runner expectations.
if ! command -v brew >/dev/null 2>&1; then
    echo 'brew not found. Install Homebrew first: https://brew.sh' >&2
    exit 1
fi
if ! brew list --formula krb5 >/dev/null 2>&1; then
    echo "==> brew install krb5"
    brew install krb5
else
    echo "==> krb5 already installed"
fi

# 2. krb5.conf. Overwrite each run -- it's small, deterministic, and
# the source of truth lives here. udp_preference_limit=1 forces TCP
# because netsh portproxy on the bench is TCP-only.
echo "==> rendering $KRB5_CONF"
mkdir -p "$(dirname "$KRB5_CONF")"
cat > "$KRB5_CONF" <<EOF
# Generated by hack/lab/kerberos/client-setup.sh -- do not edit by hand.
# Re-run \`task lab:client-setup\` to regenerate.

[libdefaults]
    default_realm = $REALM
    dns_lookup_kdc = false
    dns_lookup_realm = false
    udp_preference_limit = 1
    forwardable = true
    rdns = false

[realms]
    $REALM = {
        kdc = $DC_FQDN
        admin_server = $DC_FQDN
        default_domain = hv.lab
    }

[domain_realm]
    .hv.lab = $REALM
    hv.lab = $REALM
EOF

# 3. /etc/hosts entries. Idempotent by checking for the actual FQDN
# mapping (not a comment marker), so a manual or previously-tooled
# entry isn't duplicated. sudo prompts interactively the first time;
# subsequent runs no-op without invoking sudo at all.
need_hosts=0
grep -qE "^[[:space:]]*${BENCH_IP}[[:space:]]+.*\b${DC_FQDN}\b"    /etc/hosts || need_hosts=1
grep -qE "^[[:space:]]*${BENCH_IP}[[:space:]]+.*\b${BENCH_FQDN}\b" /etc/hosts || need_hosts=1
if [ "$need_hosts" -eq 1 ]; then
    echo "==> appending HV.LAB hosts entries to /etc/hosts (sudo)"
    sudo tee -a /etc/hosts >/dev/null <<EOF

# HV.LAB Kerberos demo (managed by hack/lab/kerberos/client-setup.sh)
$BENCH_IP	$DC_FQDN hv-dc-01
$BENCH_IP	$BENCH_FQDN hv-bench-01
EOF
else
    echo "==> /etc/hosts already maps $DC_FQDN and $BENCH_FQDN"
fi

# 4. kinit -> FILE ccache. KRB5CCNAME forces FILE: regardless of
# system default; gokrb5 only reads MIT FILE format. Pipe the password
# from .env.local so this stays non-interactive (re-runs after TGT
# expiry shouldn't require re-typing).
echo "==> kinit Administrator@$REALM (FILE ccache)"
KRB5_CONFIG="$KRB5_CONF" KRB5CCNAME="$CCACHE" \
    "$KINIT" "Administrator@$REALM" <<<"$HVLAB_ADMIN_PASSWORD"

# 5. Sanity-check the TGT and the HTTP service ticket. kvno is the
# real proof: it confirms the KDC issued a ticket for the bench's SPN,
# which means Phase 2's portproxy + SPN registration is wired right.
echo "==> klist"
KRB5_CONFIG="$KRB5_CONF" KRB5CCNAME="$CCACHE" "$KLIST"
echo "==> kvno HTTP/$BENCH_FQDN"
KRB5_CONFIG="$KRB5_CONF" KRB5CCNAME="$CCACHE" "$KVNO" "HTTP/$BENCH_FQDN"

cat <<EOF

Kerberos client ready. To run the smoke test:

    export KRB5_CONFIG="$KRB5_CONF"
    export PATH="/opt/homebrew/opt/krb5/bin:\$PATH"
    BENCH_HOST=$BENCH_FQDN \\
      BENCH_USER=Administrator@$REALM \\
      BENCH_KRB_REALM=$REALM \\
      BENCH_KRB_CCACHE="${CCACHE#FILE:}" \\
      BENCH_KRB_CONF="$KRB5_CONF" \\
      go test -tags=winrm_bench -run=TestWinRMBenchSmoke_Kerberos -v ./internal/connection/
EOF
